#!/usr/bin/env node

var path = require('path');
var repl = require('repl');
var programm = require('commander');
var app = require('./src/app.js');
var log = require('./src/log.js');
var checkVersion = require('./src/check-version.js');
var packageInfo = require('./package.json');
var config = require('./src/configProcess.js');
var inquirer = require('inquirer');

programm
	.version(packageInfo.version)
	.parse(process.argv);

checkVersion()

var appName = programm.args[0],
	output = path.join(__dirname);

if (appName) {
	inquirer.prompt([{
		type: 'list',
		name: 'appType',
		message: 'choose one of the apps!',
		choices: config.appList || []
	}]).then(function (ansers) {
		app.createApp(appName, ansers.appType, output);
	});
} else {
	log.error('appName is must!');
}
